/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked and modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdmRouteImport } from './routes/adm'
import { Route as ContagemRouteImport } from './routes/contagem'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as RetiradasRouteImport } from './routes/retiradas'
import { Route as ContagemLancarRouteImport } from './routes/contagem.lancar'
import { Route as DemoBomboniereRouteImport } from './routes/demo-bomboniere'
import { Route as DemoGestaoRouteImport } from './routes/demo-gestao'

const IndexRoute = IndexRouteImport.update({
  id: '/', path: '/', getParentRoute: () => rootRouteImport,
} as any)
const AdmRoute = AdmRouteImport.update({
  id: '/adm', path: '/adm', getParentRoute: () => rootRouteImport,
} as any)
const ContagemRoute = ContagemRouteImport.update({
  id: '/contagem', path: '/contagem', getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio', path: '/relatorio', getParentRoute: () => rootRouteImport,
} as any)
const RetiradasRoute = RetiradasRouteImport.update({
  id: '/retiradas', path: '/retiradas', getParentRoute: () => rootRouteImport,
} as any)
const ContagemLancarRoute = ContagemLancarRouteImport.update({
  id: '/lancar', path: '/lancar', getParentRoute: () => ContagemRoute,
} as any)
const DemoBomboniereRoute = DemoBomboniereRouteImport.update({
  id: '/demo-bomboniere', path: '/demo-bomboniere', getParentRoute: () => rootRouteImport,
} as any)
const DemoGestaoRoute = DemoGestaoRouteImport.update({
  id: '/demo-gestao', path: '/demo-gestao', getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adm': typeof AdmRoute
  '/contagem': typeof ContagemRouteWithChildren
  '/relatorio': typeof RelatorioRoute
  '/retiradas': typeof RetiradasRoute
  '/contagem/lancar': typeof ContagemLancarRoute
  '/demo-bomboniere': typeof DemoBomboniereRoute
  '/demo-gestao': typeof DemoGestaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adm': typeof AdmRoute
  '/contagem': typeof ContagemRouteWithChildren
  '/relatorio': typeof RelatorioRoute
  '/retiradas': typeof RetiradasRoute
  '/contagem/lancar': typeof ContagemLancarRoute
  '/demo-bomboniere': typeof DemoBomboniereRoute
  '/demo-gestao': typeof DemoGestaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adm': typeof AdmRoute
  '/contagem': typeof ContagemRouteWithChildren
  '/relatorio': typeof RelatorioRoute
  '/retiradas': typeof RetiradasRoute
  '/contagem/lancar': typeof ContagemLancarRoute
  '/demo-bomboniere': typeof DemoBomboniereRoute
  '/demo-gestao': typeof DemoGestaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adm'
    | '/contagem'
    | '/relatorio'
    | '/retiradas'
    | '/contagem/lancar'
    | '/demo-bomboniere'
    | '/demo-gestao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adm'
    | '/contagem'
    | '/relatorio'
    | '/retiradas'
    | '/contagem/lancar'
    | '/demo-bomboniere'
    | '/demo-gestao'
  id:
    | '__root__'
    | '/'
    | '/adm'
    | '/contagem'
    | '/relatorio'
    | '/retiradas'
    | '/contagem/lancar'
    | '/demo-bomboniere'
    | '/demo-gestao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmRoute: typeof AdmRoute
  ContagemRoute: typeof ContagemRouteWithChildren
  RelatorioRoute: typeof RelatorioRoute
  RetiradasRoute: typeof RetiradasRoute
  DemoBomboniereRoute: typeof DemoBomboniereRoute
  DemoGestaoRoute: typeof DemoGestaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/adm': { id: '/adm'; path: '/adm'; fullPath: '/adm'; preLoaderRoute: typeof AdmRouteImport; parentRoute: typeof rootRouteImport }
    '/contagem': { id: '/contagem'; path: '/contagem'; fullPath: '/contagem'; preLoaderRoute: typeof ContagemRouteImport; parentRoute: typeof rootRouteImport }
    '/relatorio': { id: '/relatorio'; path: '/relatorio'; fullPath: '/relatorio'; preLoaderRoute: typeof RelatorioRouteImport; parentRoute: typeof rootRouteImport }
    '/retiradas': { id: '/retiradas'; path: '/retiradas'; fullPath: '/retiradas'; preLoaderRoute: typeof RetiradasRouteImport; parentRoute: typeof rootRouteImport }
    '/contagem/lancar': { id: '/contagem/lancar'; path: '/lancar'; fullPath: '/contagem/lancar'; preLoaderRoute: typeof ContagemLancarRouteImport; parentRoute: typeof ContagemRoute }
    '/demo-bomboniere': { id: '/demo-bomboniere'; path: '/demo-bomboniere'; fullPath: '/demo-bomboniere'; preLoaderRoute: typeof DemoBomboniereRouteImport; parentRoute: typeof rootRouteImport }
    '/demo-gestao': { id: '/demo-gestao'; path: '/demo-gestao'; fullPath: '/demo-gestao'; preLoaderRoute: typeof DemoGestaoRouteImport; parentRoute: typeof rootRouteImport }
  }
}

interface ContagemRouteChildren { ContagemLancarRoute: typeof ContagemLancarRoute }
const ContagemRouteChildren: ContagemRouteChildren = { ContagemLancarRoute: ContagemLancarRoute }
const ContagemRouteWithChildren = ContagemRoute._addFileChildren(ContagemRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmRoute: AdmRoute,
  ContagemRoute: ContagemRouteWithChildren,
  RelatorioRoute: RelatorioRoute,
  RetiradasRoute: RetiradasRoute,
  DemoBomboniereRoute: DemoBomboniereRoute,
  DemoGestaoRoute: DemoGestaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
