/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContagemRouteImport } from './routes/contagem'
import { Route as RetiradasRouteImport } from './routes/retiradas'
import { Route as ContagemLancarRouteImport } from './routes/contagem.lancar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContagemRoute = ContagemRouteImport.update({
  id: '/contagem',
  path: '/contagem',
  getParentRoute: () => rootRouteImport,
} as any)
const RetiradasRoute = RetiradasRouteImport.update({
  id: '/retiradas',
  path: '/retiradas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContagemLancarRoute = ContagemLancarRouteImport.update({
  id: '/lancar',
  path: '/lancar',
  getParentRoute: () => ContagemRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contagem': typeof ContagemRouteWithChildren
  '/retiradas': typeof RetiradasRoute
  '/contagem/lancar': typeof ContagemLancarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contagem': typeof ContagemRouteWithChildren
  '/retiradas': typeof RetiradasRoute
  '/contagem/lancar': typeof ContagemLancarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contagem': typeof ContagemRouteWithChildren
  '/retiradas': typeof RetiradasRoute
  '/contagem/lancar': typeof ContagemLancarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contagem' | '/retiradas' | '/contagem/lancar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contagem' | '/retiradas' | '/contagem/lancar'
  id: '__root__' | '/' | '/contagem' | '/retiradas' | '/contagem/lancar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContagemRoute: typeof ContagemRouteWithChildren
  RetiradasRoute: typeof RetiradasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contagem': {
      id: '/contagem'
      path: '/contagem'
      fullPath: '/contagem'
      preLoaderRoute: typeof ContagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retiradas': {
      id: '/retiradas'
      path: '/retiradas'
      fullPath: '/retiradas'
      preLoaderRoute: typeof RetiradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contagem/lancar': {
      id: '/contagem/lancar'
      path: '/lancar'
      fullPath: '/contagem/lancar'
      preLoaderRoute: typeof ContagemLancarRouteImport
      parentRoute: typeof ContagemRoute
    }
  }
}

interface ContagemRouteChildren {
  ContagemLancarRoute: typeof ContagemLancarRoute
}

const ContagemRouteChildren: ContagemRouteChildren = {
  ContagemLancarRoute: ContagemLancarRoute,
}

const ContagemRouteWithChildren = ContagemRoute._addFileChildren(
  ContagemRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContagemRoute: ContagemRouteWithChildren,
  RetiradasRoute: RetiradasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
